name: far_glory_construction_dashboard
description: Far Glory Construction Site DashBoard
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  video_player: ^2.6.0
  syncfusion_flutter_charts: ^21.1.35
  intl: any
  flutter_localizations:
    sdk: flutter
  #assets_audio_player: ^3.0.6
  flutter_ringtone_player: ^3.2.0
  #flutter_tts: ^3.6.3
  #js: ^0.6.7
  toggle_switch: ^2.1.0
  path:


dev_dependencies:
  flutter_test:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  freezed: ^2.3.2
  pmvvm: ^4.0.1
  mqtt_client: ^9.6.3
  get_it: ^6.0.0
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.0
  #rxdart: ^0.27.5
  path_provider: ^2.0.11
  http: ^0.13.4
  flutter_native_timezone: ^2.0.0
  flutter_vlc_player: ^7.2.0
  video_player: ^2.5.1
  webview_flutter: ^4.0.4
  permission_handler: ^10.2.0
  flutter_inappwebview: ^6.0.0-beta.22
  url_launcher: ^6.1.9
  platform_device_id: ^1.0.1
  image: ^4.0.15
  stomp_dart_client: ^0.4.4
  shared_preferences: ^2.1.1
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_svg: ^2.0.5
  intl_translation: ^0.18.2
  path: ^1.8.0
  sqflite: ^2.2.8+4



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/weather.json
#    - images/check1.png
#    - images/check2.png
#    - images/check3.png
#    - images/worker4.png
#    - images/worker4.png
#    - images/worker5.png
    - images/
#    - images/aidesk_spec.jpg
#    - images/weather1_bak.png
#    - images/wather1.jpg
#    - images/weather2.png
    - videos/demo1.mp4
    - videos/demo2.mp4
    - videos/demo3.mp4
    - assets/audios/blacklist.mp3


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
