// To parse this JSON data, do
//
//     final settingItem = settingItemFromJson(jsonString);

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'dart:convert';

part 'SettingItem.freezed.dart';
part 'SettingItem.g.dart';
//auto generated by
// " flutter pub run build_runner build"

SettingData settingDataFromJson(String str) => SettingData.fromJson(json.decode(str));
String settingDataToJson(SettingData data) => json.encode(data);

SettingItem settingItemFromJson(String str) => SettingItem.fromJson(json.decode(str));
String settingItemToJson(SettingItem data) => json.encode(data);

@freezed
class SettingData with _$SettingData {
  const factory SettingData({
    int? page,
    int? total,
    List<SettingItem>? result,
    int? PageSize,
  }) = _SettingData;

  factory SettingData.fromJson(Map<String, dynamic> json) => _$SettingDataFromJson(json);
}

@freezed
class SettingItem with _$SettingItem {
  const factory SettingItem({
    int? id,
    String? resultVar,
    String? val,
    String? type,
    String? name,
    String? memo,
  }) = _SettingItem;

  factory SettingItem.fromJson(Map<String, dynamic> json) => _$SettingItemFromJson(json);
}
